name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [net8.0, net10.0]
    runs-on: k8s-linux
    env:
      DOTNET_INSTALL_DIR: ${{ github.workspace }}/.dotnet
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Restore test dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c release -f ${{ matrix.target }} --no-restore
