name: Release Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        target: [net8.0, net10.0]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Restore test dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c release -f ${{ matrix.target }} --no-restore

  publish:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Build NuGet Package
        run: dotnet pack -c Release -p:PackageVersion=${{  github.ref_name }}

      - name: Upload nuget package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nuget package
          path: "**/*.nupkg"

      - name: Publish NuGet Package
        run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
